// Traducciones
const traducciones = {
    'titulo': {
     'es': 'Creditos de carbono',
     'en': 'Carbon credits'
   },
   'inicio': {
     'es': 'Inicio',
     'en': 'Home'
   },
   'pagina': {
     'es': 'Páginas',
     'en': 'Pages'
   },
     'aboutcompany': {
       'es': 'Sobre la compañìa',
       'en': 'About company'
     },
     'platform': {
       'es': 'Plataforma',
       'en': 'Platform'
     },
     'commingsoon': {
       'es': 'Muy pronto',
       'en': 'Comming soon'
     },
     'creditos': {
        'es': 'Creditos de carbono',
        'en': 'Carbon credits'
      },
      'certificate': {
        'es': 'Certificado de Autenticidad',
        'en': 'Certificate of Authenticity'
      },
     'investment': {
       'es': 'Oportunidades de inversión',
       'en': 'Investment Opportunitties'
     },
     'marketplace': {
       'es': 'Marketplace',
       'en': 'Marketplace'
     },
     'elements': {
       'es': 'Contacto',
       'en': 'Contact'
     },
     'teammembers': {
       'es': 'Miembros del equipo',
       'en': 'Team Members'
     },
     'contactform': {
       'es': 'Formulario de contacto',
       'en': 'Contact form'
     },
     'carbon': {
        'es': 'Creditos de carbono',
        'en': 'Carbon credits'
      },
      'creditos1': {
        'es': 'Creditos de carbono',
        'en': 'Carbon credits'
      },
      'creditos2': {
        'es': 'Creditos de carbono',
        'en': 'Carbon credits'
      },
      'parrafo1': {
        'es': 'Son certificados intercambiables que se comercializan bajo los mercados de carbono y que pueden representar:',
        'en': 'They are interchangeable certificates traded within carbon markets, which can represent:'
      },
      'parrafo2': {
        'es': '-El derecho a emitir una tonelada de dióxido de carbono equivalente (tCO2e).',
        'en': '-The right to emit one ton of carbon dioxide equivalent (tCO2e).'
      },
      'parrafo3': {
        'es': '-La reducción o remoción de una tCO2e de la atmósfera, que se usa para compensar emisiones de GEI.',
        'en': '-The reduction or removal of one tCO2e from the atmosphere, used to offset greenhouse gas emissions.'
      },
      'parrafo4': {
        'es': 'Muchas veces la expresión “bono de carbono” presta lugar a confusiones, ya que suele confundirse con “bono verde”, aunque no guardan ningún tipo de relación.',
        'en': 'Often, the term carbon bond leads to confusion, as it is frequently mistaken for a green bond, although they are unrelated.'
      },
      'parrafo5': {
        'es': 'Bajo los mecanismos de compensación, los créditos de carbono son generados por proyectos que buscan evitar, reducir o eliminar emisiones de GEI de la atmósfera. Estos proyectos pueden ser desarrollados por actores del sector privado, público y de organizaciones no gubernamentales.Además, pueden involucrar distintos tipos de actividades, como las relacionadas con energías renovables, la conservación y reforestación de bosques, las medidas de eficiencia energética y la reducción de emisiones de metano.',
        'en': 'Under offset mechanisms, carbon credits are generated by projects aiming to prevent, reduce, or eliminate greenhouse gas emissions from the atmosphere. These projects can be undertaken by actors from the private, public, and non-governmental organization sectors. Furthermore, they can encompass various types of activities, such as those related to renewable energy, forest conservation and reforestation, energy efficiency measures, and methane emission reduction'
      },
      'parrafo6': {
        'es': 'Para que un proyecto pueda participar en un mercado de carbono deberá cumplir con los estándares del mercado regulado o del voluntario y así certificar los créditos de carbono que el proyecto genera. Cada tonelada de emisiones evitada, reducida o eliminada y certificada genera un crédito de carbono.',
        'en': 'For a project to participate in a carbon market, it must adhere to the standards of either the regulated or voluntary market and thereby certify the carbon credits the project generates. Each ton of avoided, reduced, or eliminated emissions that is certified generates a carbon credit.'
      },
      'mercados': {
        'es': 'Mercados de carbono',
        'en': 'Carbon markets'
      },
      'mercados1': {
        'es': 'Los mercados de carbono son sistemas en donde gobiernos, empresas e individuos pueden comprar y vender unidades (créditos), ya sea para respaldar las emisiones de GEI o bien para compensarlas.',
        'en': 'Carbon markets are systems where governments, companies, and individuals can buy and sell units (credits), either to offset greenhouse gas emissions or to compensate for them.'
      },
      'mercados2': {
        'es': 'Se plantean como instrumentos para abordar la actual crisis climática, desencadenada por la acumulación de GEI en la atmósfera',
        'en': 'They are proposed as instruments to address the current climate crisis, triggered by the accumulation of greenhouse gases in the atmosphere.'
      },
      'mercados3': {
        'es': 'Hay dos tipos de mercados de carbono:',
        'en': 'There are two types of carbon markets:'
      },
      'mercados4': {
        'es': '•Regulados (o de cumplimiento): sistemas que funcionan a partir de obligaciones o tratados para la reducción de emisiones. Están regulados por gobiernos u organismos multilaterales.',
        'en': '• Regulated (or compliance) markets: systems that operate based on obligations or treaties for emission reduction. They are regulated by governments or multilateral organizations.'
      },
      'mercados5': {
        'es': '•Voluntarios: funcionan por fuera de los mercados oficiales y permiten a las empresas u otras entidades comprar créditos de carbono para compensar voluntariamente sus emisiones. No están regulados por los gobiernos y operan sin un tope de emisiones.',
        'en': '• Voluntary markets: operate outside of official markets and allow companies or other entities to voluntarily purchase carbon credits to offset their emissions. They are not regulated by governments and operate without an emissions cap.'
      },
      'como': {
        'es': '¿Cómo funcionan los distintos mercados de carbono?',
        'en': 'How do different carbon markets work?'
      },
      'como1': {
        'es': 'No todos los mercados de carbono operan de la misma manera ni intercambian el mismo tipo de unidades',
        'en': 'Not all carbon markets operate in the same way or exchange the same type of units.'
      },
      'como2': {
        'es': 'En este sentido, se pueden distinguir dos tipos, según su funcionamiento:',
        'en': 'In this sense, two types can be distinguished based on their operation:'
      },
      'como3': {
        'es': '-Sistemas de comercio de emisiones (ETS, por su sigla en inglés): en estos esquemas de “tope y canje” se establece un límite global de emisiones para la región abarcada, que luego se traduce en créditos que representan derechos de emisión, es decir, respaldos para la emisión de GEI.',
        'en': '-Emissions Trading Systems (ETS): In these "cap and trade" schemes, a global emissions limit is set for the covered region, which is then translated into credits representing emission rights, that is, allowances for the emission of GEI.'
      },
      'como4': {
        'es': 'Estos derechos de emisión son asignados a las entidades cubiertas por el sistema (en su mayoría, empresas), que luego los comercializan en un mercado de carbono interno. Por ejemplo, si el   límite de emisiones anuales asignado a una empresa es de 10 toneladas de CO2 (tCO2) y a final de año solo emitió 6 tCO 2 en total, esta puede elegir vender las 4 tCO 2 restantes a otra empresa que haya superado su límite de emisiones y busque evitar penalidades.',
        'en': 'These emission rights are allocated to entities covered by the system (mostly companies), which then trade them in an internal carbon market. For instance, if a company is allocated an annual emissions limit of 10 tons of CO2 (tCO2), and by the end of the year, it has only emitted a total of 6 tCO2, it can choose to sell the remaining 4 tCO2 to another company that has exceeded its emissions limit and seeks to avoid penalties.'
      },
      'como5': {
        'es': '-Mecanismos de compensación: a diferencia de los esquemas de tope y canje, las unidades intercambiadas no representan derechos de emisión, sino reducciones de emisiones alcanzadas a través de proyectos de mitigación. Bajo esta lógica, un país, empresa o individuo puede “neutralizar” sus emisiones de GEI adquiriendo créditos de carbono  y financiando así proyectos que buscan reducir emisiones o capturar GEI de la atmósfera.',
        'en': '-Offset Mechanisms: Unlike cap and trade schemes, the exchanged units do not represent emission rights but rather emissions reductions achieved through mitigation projects. Following this logic, a country, company, or individual can "offset" their GHG emissions by acquiring carbon credits and thereby funding projects aimed at reducing emissions or capturing GHGs from the atmosphere.'
      },
      'tokenizacion': {
        'es': 'Tokenización de Créditos de Carbono: Solucionando desafíos fundamentales del mercado',
        'en': 'Tokenization of Carbon Credits: Addressing Fundamental Market Challenges'
      },
      'tokenizacion1': {
        'es': 'Escalando el financiamiento climático con expertos en el mercado del Carbono: Experiencia, Compatibilidad e Integridad en Acción',
        'en': 'Scaling Climate Financing with Carbon Market Experts: Experience, Compatibility, and Integrity in Action'
      },
      'claridad': {
        'es': 'Transparencia',
        'en': 'Transparency'
      },
      'claridadp': {
        'es': 'Nuestra plataforma usa una base de datos abierta con tecnología de Blockchain para registrar información de créditos de carbono. Priorizamos la transparencia para fomentar confianza en el mercado y promover la lucha contra el cambio climático.',
        'en': 'Our platform utilizes an open database with blockchain technology to record carbon credit information. We prioritize transparency to foster trust in the market and advance the fight against climate change.'
      },
      'maestria': {
        'es': 'Experiencia',
        'en': 'Experience'
      },
      'maestriap': {
        'es': 'Trabajamos junto a especialistas en VCM y registros de emisiones, aprovechando nuestra pericia para maximizar la utilización de tecnologías emergentes en la administración de créditos de carbono y asegurando una acción	climática robusta y sostenible.',
        'en': 'We collaborate closely with experts in emissions trading systems and emissions registries, leveraging our expertise to maximize the use of emerging technologies in carbon credit management. This ensures a strong and sustainable climate action.'
      },
      'flexibilidad': {
        'es': 'Flexibilidad',
        'en': 'Flexibility'
      },
      'flexibilidadp': {
        'es': 'La plataforma de Tokensur vincula créditos de carbono con aplicaciones de blockchain, abriendo así un mundo de posibilidades para la innovación en productos climáticos sostenibles y brindando incentivos para impulsar la acción climática a escala global',
        'en': 'The Tokensur platform links carbon credits with blockchain applications, thus opening up a world of possibilities for innovation in sustainable climate products and providing incentives to drive global-scale climate action.'
      },
      'certificados': {
        'es': 'CERTIFICADOS DE COMPENSACIÓN DE CARBONO DE TOKENSUR',
        'en': 'TOKENSUR CARBON OFFSET CERTIFICATES'
      },
      'certificados1': {
        'es': 'Tokensur ha aceptado la sostenibilidad ambiental como un objetivo fundamental y se dedica formalmente a las operaciones de red de carbono negativo mediante la compra trimestral de compensaciones de carbono en cantidades especificadas por un proveedor de evaluación independiente, ClimateTrade.',
        'en': 'Tokensur has embraced environmental sustainability as a core objective and is formally committed to negative carbon network operations through quarterly purchases of carbon offsets in specified amounts from an independent assessment provider, ClimateTrade.'
      },
      'certificados2': {
        'es': 'Después de cada trimestre, se calculan las evaluaciones de emisiones y se compran créditos, que representan los aumentos en el uso de la red, para compensar el trimestre futuro. El informe de verificación preparado por ClimateTrade y procesado por NotRZR Consensus Service ("NCS") verifica el carbono secuestrado por varios proyectos de secuestro de carbono.',
        'en': 'After each quarter, emissions assessments are calculated, and credits are purchased, representing the increases in network usage, to offset the upcoming quarter. The verification report prepared by ClimateTrade and processed by the NotRZR Consensus Service ("NCS") validates the carbon sequestered by various carbon capture projects.'
      },
      'certificados3': {
        'es': 'Patagonia Hashers LLC y Tokensur llegaron a esta elección después de una discusión, y esperamos que nuestra decisión aliente a otras redes públicas a seguir procedimientos operativos ambientalmente responsables.',
        'en': 'Patagonia Hashers LLC and Tokensur arrived at this decision after a discussion, and we hope that our choice will encourage other public networks to adopt environmentally responsible operational procedures.'
      },
      'certificados4': {
        'es': 'Las emisiones operativas de la plataforma y red de Tokensur durante el primer trimestre de 2023 fueron de 20 toneladas de dióxido de carbono. Según la calculadora de equivalencia de gases de efecto invernadero de la EPA, esta cantidad de CO2 es comparable a un año de conducción de 4,3 automóviles de pasajeros a gasolina.',
        'en': 'The operational emissions of the Tokensur platform and network during the first quarter of 2023 amounted to 20 metric tons of carbon dioxide. According to the EPAs greenhouse gas equivalency calculator, this amount of CO2 is equivalent to a year of driving 4.3 gasoline-powered passenger cars.'
      },
      'certificados5': {
        'es': 'Para comprender el programa, lea "Convertirse en carbono negativo en las operaciones Blockchain de Tokensur".',
        'en': 'To understand the program, please read "Becoming Carbon Negative in Tokensurs Blockchain Operations."'
      }, 
      'validaciones': {
        'es': 'COMPENSACIÓN DE CARBONO DEL TRIMESTRE 1-2023',
        'en': 'CARBON OFFSET OF QUARTER 1-2023'
      },
      'btn-validaciones': {
        'es': 'Ver certificado adquirido',
        'en': 'View certificate acquired'
      },
      'btn-validaciones1': {
        'es': 'Ver validación en Notardec',
        'en': 'View validation in Notardec'
      },
      'texto-btns': {
        'es': 'En 2022, la red Tokensur emitió toneladas métricas de CO2. Para compensar esto, Tokensur compró compensaciones por la misma cantidad de CO2 en 2023. Según la calculadora de equivalencia de gases de efecto invernadero de la EPA, las emisiones de la red Hedera fueron equivalentes a los gases de efecto invernadero producidos por vehículos de pasajeros a gasolina que circulan durante un año.',
        'en': 'In 2022, the Tokensur network emitted metric tonnes of CO2. To offset this, Tokensur purchased offsets for the same amount of CO2 in 2023. Based on the EPA´s greenhouse gas equivalency calculator, the emissions from the Hedera network were equivalent to the greenhouse gases produced by gasoline-powered passenger vehicles being driven for one year.'
      },
      'validaciones2': {
        'es': 'COMPENSACIÓN DE CARBONO DEL TRIMESTRE 1-2023',
        'en': 'CARBON OFFSET OF QUARTER 1-2023'
      },
      'btn-validaciones2': {
        'es': 'Ver certificado adquirido',
        'en': 'View certificate acquired'
      },
      'btn-validaciones3': {
        'es': 'Ver validación en Notardec',
        'en': 'View validation in Notardec'
      },
      'texto-btns2': {
        'es': 'En 2022, la red Tokensur emitió toneladas métricas de CO2. Para compensar esto, Tokensur compró compensaciones por la misma cantidad de CO2 en 2023. Según la calculadora de equivalencia de gases de efecto invernadero de la EPA, las emisiones de la red Hedera fueron equivalentes a los gases de efecto invernadero producidos por vehículos de pasajeros a gasolina que circulan durante un año.',
        'en': 'In 2022, the Tokensur network emitted metric tonnes of CO2. To offset this, Tokensur purchased offsets for the same amount of CO2 in 2023. Based on the EPA´s greenhouse gas equivalency calculator, the emissions from the Hedera network were equivalent to the greenhouse gases produced by gasoline-powered passenger vehicles being driven for one year.'
      },
      'validaciones3': {
        'es': 'COMPENSACIÓN DE CARBONO DEL TRIMESTRE 1-2023',
        'en': 'CARBON OFFSET OF QUARTER 1-2023'
      },
      'btn-validaciones4': {
        'es': 'Ver certificado adquirido',
        'en': 'View certificate acquired'
      },
      'btn-validaciones5': {
        'es': 'Ver validación en Notardec',
        'en': 'View validation in Notardec'
      },
      'texto-btns3': {
        'es': 'En 2022, la red Tokensur emitió toneladas métricas de CO2. Para compensar esto, Tokensur compró compensaciones por la misma cantidad de CO2 en 2023. Según la calculadora de equivalencia de gases de efecto invernadero de la EPA, las emisiones de la red Hedera fueron equivalentes a los gases de efecto invernadero producidos por vehículos de pasajeros a gasolina que circulan durante un año.',
        'en': 'In 2022, the Tokensur network emitted metric tonnes of CO2. To offset this, Tokensur purchased offsets for the same amount of CO2 in 2023. Based on the EPA´s greenhouse gas equivalency calculator, the emissions from the Hedera network were equivalent to the greenhouse gases produced by gasoline-powered passenger vehicles being driven for one year.'
      },
      'calculator': {
        'es': 'Calcula tu huella de carbono anual',
        'en': 'Calculate your annual carbon footprint'
      },
     'footer1': {
       'es': 'Inicio',
       'en': 'Home'
     },
     'footer2': {
       'es': 'Sobre la compañía',
       'en': 'About company'
     },
     'footer3': {
       'es': 'Plataforma',
       'en': 'Platform'
     },
     'footer4': {
       'es': 'Muy pronto',
       'en': 'Commingsoon'
     },
     'footer-pol': {
       'es': 'Politica de privacidad',
       'en': 'Privacy Policy'
     },
     'footer5': {
       'es': 'Marketplace',
       'en': 'Marketplace'
     },
     'footer6': {
       'es': 'Miembros del equipo',
       'en': 'Team members'
     },
     'footer7': {
       'es': 'Formulario de contacto',
       'en': 'Contact form'
     },
     'footer8': {
       'es': 'Agendá una reunión',
       'en': 'Scheudle a meeting'
     },
     'footer9': {
       'es': 'Terminos de uso',
       'en': 'Terms of use'
     },
     'footer10': {
       'es': 'Aviso legal',
       'en': 'Legal notice'
     },
 
 };
 
 function cambiarIdioma(idioma) {
   localStorage.setItem('idioma', idioma);
   aplicarTraducciones();
  }
 
 // Función para cambiar el idioma
   function aplicarTraducciones() {
   const idioma = localStorage.getItem('idioma') || 'es';
   document.getElementById('titulo').innerHTML = traducciones['titulo'][idioma];
   document.getElementById('inicio').innerHTML = traducciones['inicio'][idioma];
   document.getElementById('pagina').innerHTML = traducciones['pagina'][idioma];
   document.getElementById('aboutcompany').innerHTML = traducciones['aboutcompany'][idioma];
   document.getElementById('platform').innerHTML = traducciones['platform'][idioma];
   document.getElementById('commingsoon').innerHTML = traducciones['commingsoon'][idioma];
   document.getElementById('creditos').innerHTML = traducciones['creditos'][idioma];
   document.getElementById('certificate').innerHTML = traducciones['certificate'][idioma];
   document.getElementById('investment').innerHTML = traducciones['investment'][idioma];
   document.getElementById('marketplace').innerHTML = traducciones['marketplace'][idioma];
   document.getElementById('elements').innerHTML = traducciones['elements'][idioma];
   document.getElementById('teammembers').innerHTML = traducciones['teammembers'][idioma];
   document.getElementById('contactform').innerHTML = traducciones['contactform'][idioma];
   document.getElementById('carbon').innerHTML = traducciones['carbon'][idioma];
   document.getElementById('creditos1').innerHTML = traducciones['creditos1'][idioma];
   document.getElementById('creditos2').innerHTML = traducciones['creditos2'][idioma];
   document.getElementById('parrafo1').innerHTML = traducciones['parrafo1'][idioma];
   document.getElementById('parrafo2').innerHTML = traducciones['parrafo2'][idioma];
   document.getElementById('parrafo3').innerHTML = traducciones['parrafo3'][idioma];
   document.getElementById('parrafo4').innerHTML = traducciones['parrafo4'][idioma];
   document.getElementById('parrafo5').innerHTML = traducciones['parrafo5'][idioma];
   document.getElementById('parrafo6').innerHTML = traducciones['parrafo6'][idioma];
   document.getElementById('mercados').innerHTML = traducciones['mercados'][idioma];
   document.getElementById('mercados1').innerHTML = traducciones['mercados1'][idioma];
   document.getElementById('mercados2').innerHTML = traducciones['mercados2'][idioma];
   document.getElementById('mercados3').innerHTML = traducciones['mercados3'][idioma];
   document.getElementById('mercados4').innerHTML = traducciones['mercados4'][idioma];
   document.getElementById('mercados5').innerHTML = traducciones['mercados5'][idioma];
   document.getElementById('como').innerHTML = traducciones['como'][idioma];
   document.getElementById('como1').innerHTML = traducciones['como1'][idioma];
   document.getElementById('como2').innerHTML = traducciones['como2'][idioma];
   document.getElementById('como3').innerHTML = traducciones['como3'][idioma];
   document.getElementById('como4').innerHTML = traducciones['como4'][idioma];
   document.getElementById('como5').innerHTML = traducciones['como5'][idioma];
   document.getElementById('tokenizacion').innerHTML = traducciones['tokenizacion'][idioma];
   document.getElementById('tokenizacion1').innerHTML = traducciones['tokenizacion1'][idioma];
   document.getElementById('claridad').innerHTML = traducciones['claridad'][idioma];
   document.getElementById('claridadp').innerHTML = traducciones['claridadp'][idioma];
   document.getElementById('maestria').innerHTML = traducciones['maestria'][idioma];
   document.getElementById('maestriap').innerHTML = traducciones['maestriap'][idioma];
   document.getElementById('flexibilidad').innerHTML = traducciones['flexibilidad'][idioma];
   document.getElementById('flexibilidadp').innerHTML = traducciones['flexibilidadp'][idioma];
   document.getElementById('certificados').innerHTML = traducciones['certificados'][idioma];
   document.getElementById('certificados1').innerHTML = traducciones['certificados1'][idioma];
   document.getElementById('certificados2').innerHTML = traducciones['certificados2'][idioma];
   document.getElementById('certificados3').innerHTML = traducciones['certificados3'][idioma];
   document.getElementById('certificados5').innerHTML = traducciones['certificados5'][idioma];
   document.getElementById('validaciones').innerHTML = traducciones['validaciones'][idioma];
   document.getElementById('btn-validaciones').innerHTML = traducciones['btn-validaciones'][idioma];
   document.getElementById('btn-validaciones1').innerHTML = traducciones['btn-validaciones1'][idioma];
   document.getElementById('texto-btns').innerHTML = traducciones['texto-btns'][idioma];
   document.getElementById('validaciones2').innerHTML = traducciones['validaciones2'][idioma];
   document.getElementById('btn-validaciones2').innerHTML = traducciones['btn-validaciones2'][idioma];
   document.getElementById('btn-validaciones3').innerHTML = traducciones['btn-validaciones3'][idioma];
   document.getElementById('texto-btns2').innerHTML = traducciones['texto-btns2'][idioma];
   document.getElementById('validaciones3').innerHTML = traducciones['validaciones3'][idioma];
   document.getElementById('btn-validaciones4').innerHTML = traducciones['btn-validaciones4'][idioma];
   document.getElementById('btn-validaciones5').innerHTML = traducciones['btn-validaciones5'][idioma];
   document.getElementById('texto-btns3').innerHTML = traducciones['texto-btns3'][idioma];
   document.getElementById('calculator').innerHTML = traducciones['calculator'][idioma];
   document.getElementById('footer1').innerHTML = traducciones['footer1'][idioma];
   document.getElementById('footer2').innerHTML = traducciones['footer2'][idioma];
   document.getElementById('footer3').innerHTML = traducciones['footer3'][idioma];
   document.getElementById('footer4').innerHTML = traducciones['footer4'][idioma];
   document.getElementById('footer-pol').innerHTML = traducciones['footer-pol'][idioma];
   document.getElementById('footer5').innerHTML = traducciones['footer5'][idioma];
   document.getElementById('footer6').innerHTML = traducciones['footer6'][idioma];
   document.getElementById('footer7').innerHTML = traducciones['footer7'][idioma];
   document.getElementById('footer8').innerHTML = traducciones['footer8'][idioma];
   document.getElementById('footer9').innerHTML = traducciones['footer9'][idioma];
   document.getElementById('footer10').innerHTML = traducciones['footer10'][idioma];
 
 }
 
 // EventListeners para los botones
 document.getElementById('btn-es').addEventListener('click', function() {
   cambiarIdioma('es');
 });
 
 document.getElementById('btn-en').addEventListener('click', function() {
   cambiarIdioma('en');
 });
 
 window.addEventListener('DOMContentLoaded', function() {
   aplicarTraducciones();
 });